server:
  port: 8088

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/desert45/Bussiness-Banking-Project.git
          search-paths: config-data
  application:
    name: config-service